application: rekrytask
version: 1
runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: build/css

- url: /js
  static_dir: build/js

- url: /img
  static_dir: build/img

- url: /templates
  static_dir: build/templates

- url: /.*
  script: index.php